name: 'Install jw tools'
description: 'Install OpenWatcom-derived development tools'
inputs:
  jwasm:
    description: 'Install jwasm'
    default: false
  jwlink:
    description: 'Install jwlink'
    default: false
  jwlib:
    description: 'Install jwlib'
    default: false
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v2
      id: cache-jwasm
      with:
        path: bin/jwasm*
        key: jwasm2-${{ runner.os }}-${{ inputs.jwasm }}
    - uses: actions/cache@v2
      id: cache-jwlink
      with:
        path: bin/jwlink*
        key: jwlink2-${{ runner.os }}-${{ inputs.jwlink }}
    - uses: actions/cache@v2
      id: cache-jwlib
      with:
        path: bin/jwlib*
        key: jwlib2-${{ runner.os }}-${{ inputs.jwlib }}
    - run: |
        if [ ${{ runner.os }} == Linux ]
        then
          binary_ext=
          os_letter=l
          os_name=linux
          jwasm_sha1=92d491dca098a45ef4813376561164270047d4ea
          jwlink_sha1=3ad4f2a73a98c24e9fdecf48d3773626a2369bf0
          jwlin_sha1=130e66eeef4d67310333eeffda09374cf35f8d3b
        fi
        if [ ${{ runner.os }} == Windows ]
        then
          binary_ext=.exe
          os_letter=w
          os_name=win32
          jwasm_sha1=118e1cb00b6bd21eee42ff5bd4a2f7cb46e65ba0
          jwlink_sha1=457350480f040b3e872b3eb57e2c0f98eba7ebc4
          jwlin_sha1=993f0ce2657afe9b94cba9f6c600aeca2b2f8284
        fi
        if ${{ inputs.jwasm }};
        then
          [ -f "$GITHUB_WORKSPACE"/bin/jwasm${binary_ext} ] || {
            curl https://www.japheth.de/Download/JWasm/JWasm211b${os_letter}.zip > '${{ runner.temp }}'/jwasm.zip
            mkdir -p "$GITHUB_WORKSPACE"/bin
            unzip -C -p '${{ runner.temp }}'/jwasm.zip jwasm${binary_ext} > "$GITHUB_WORKSPACE"/bin/jwasm${binary_ext}
          }
          chmod 755 bin/jwasm${binary_ext}
          actual_sha1=$(sha1sum bin/jwasm${binary_ext} | cut -c 1-40)
          if ! [ $actual_sha1 == $jwasm_sha1 ]
          then
            echo JWasm checksum $actual_sha1 doesn\'t match expected $jwasm_sha1
            exit 1
          fi
        fi
        if ${{ inputs.jwlink }};
        then
          [ -f "$GITHUB_WORKSPACE"/bin/jwlink${binary_ext} ] || {
            curl https://www.japheth.de/Download/JWlink/JWlink_v19b13_${os_name}.zip > '${{ runner.temp }}'/jwlink.zip
            mkdir -p "$GITHUB_WORKSPACE"/bin
            unzip -C -p '${{ runner.temp }}'/jwlink.zip jwlink${binary_ext} > "$GITHUB_WORKSPACE"/bin/jwlink${binary_ext}
          }
          chmod 755 bin/jwlink${binary_ext}
          actual_sha1=$(sha1sum bin/jwlink${binary_ext} | cut -c 1-40)
          if ! [ $actual_sha1 == $jwlink_sha1 ]
          then
            echo JWlink checksum $actual_sha1 doesn\'t match expected $jwlink_sha1
            exit 1
          fi
        fi
        if ${{ inputs.jwlib }};
        then
          [ -f "$GITHUB_WORKSPACE"/bin/jwlib${binary_ext} ] || {
            [ -f '${{ runner.temp }}'/jwlink.zip ] || curl https://www.japheth.de/Download/JWlink/JWlink_v19b13_${os_name}.zip > '${{ runner.temp }}'/jwlink.zip
            mkdir -p "$GITHUB_WORKSPACE"/bin
            unzip -C -p '${{ runner.temp }}'/jwlink.zip jwlib${binary_ext} > "$GITHUB_WORKSPACE"/bin/jwlib${binary_ext}
          }
          chmod 755 bin/jwlib${binary_ext}
          actual_sha1=$(sha1sum bin/jwlib${binary_ext} | cut -c 1-40)
          if ! [ $actual_sha1 == $jwlib_sha1 ]
          then
            echo JWlib checksum $actual_sha1 doesn\'t match expected $jwlib_sha1
            exit 1
          fi
        fi
        echo "$GITHUB_WORKSPACE"/bin >> $GITHUB_PATH
      shell: 'bash'
