name: 'Install jw tools'
description: 'Install OpenWatcom-derived development tools'
inputs:
  wasm:
    description: 'Install wasm'
    default: false
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v2
      id: cache-jwasm
      with:
        path: bin/jwasm
        key: jwasm-${{ runner.os }}
    - run: |
        [ -f "$GITHUB_WORKSPACE"/bin/jwasm ] || {
          curl https://www.japheth.de/Download/JWasm/JWasm211bl.zip > ${{ runner.temp }}/jwasm.zip
          mkdir "$GITHUB_WORKSPACE"/bin
          unzip -p ${{ runner.temp }}/jwasm.zip jwasm > "$GITHUB_WORKSPACE"/bin/jwasm
          chmod 755 bin/jwasm
          echo "$GITHUB_WORKSPACE"/bin >> $GITHUB_PATH
        }
      shell: 'bash'
